version: "3.9"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - solid
    networks:
      public:
        aliases:
          - api.local

  # graphs:
  #   build: ./graphs
  #   volumes:
  #     - ./graphs/src:/app/src
  #     - ./graphs/node_modules/:/app/node_modules
  #   ports:
  #     - "5173:5173"
  #   expose:
  #     - "5173"
  #   networks:
  #     - public
  #     - internal

  solid:
    build: ./pipeline/
    command: /app/pipeline/auth-pipeline.ttl
    depends_on:
      - php
    volumes:
      - ./data/:/app/pipeline/ldes/
      - ./pipeline/pipeline/:/app/pipeline/
      - ./pipeline/lib/:/app/lib/
      - ./pipeline/node_modules/:/app/node_modules/
    environment:
      DEBUG: rdfc
      groupHistory: http://php/history.php?groups
      userHistory: http://php/history.php?users
      sensorHistory: http://php/history.php?sensors
      baseUrl: "http://api.local" 
      # baseUrl: "https://another.mumodashboard.be/" 
    networks:
      - public
    expose:
      - "3000"
      - "3002"

  pipeline:
    build: ./pipeline/
    command: /app/pipeline/pipeline.ttl
    depends_on:
      - php
    volumes:
      - ./data/:/app/pipeline/ldes/
      - ./pipeline/pipeline/:/app/pipeline/
    environment:
      # DEBUG: rdfc
      groupHistory: http://php/history.php?groups
      userHistory: http://php/history.php?users
      sensorHistory: http://php/history.php?sensors
      dataHistory: http://php/history.php?data
    networks:
      - public

  # Dashboard containers
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mumo_test
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    expose:
      - "3306"
    volumes:
      - ./db_data:/var/lib/mysql
      - ./dashboard/database_withDeviceChannelIndex.sql:/docker-entrypoint-initdb.d/database.sql
    networks:
      - public

  php:
    build: ./dashboard/
    depends_on:
      - db
    expose:
      - "80"
    volumes:
      - ./dashboard/:/var/www/html
      - ./settings.php:/var/www/html/settings.php
    networks:
      - public
      
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    expose:
      - "8080"
    networks:
      - public

networks:
  public:
